server:
  port: 8083
  error:
    include-message: always

spring:
  application:
    name: leave-service

  datasource:
    url: jdbc:postgresql://localhost:5432/leavemanagement
    username: postgres
    password: Amulya1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        default_schema: leave

  mail:
    host: smtp.gmail.com
    port: 587
    username: amulyachodisetty2004@gmail.com
    password: fekg njti gujr btuk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    sender: amulyachodisetty2004@gmail.com
    manager: amulyachodisetty0@gmail.com
    admin: amulyachodisetty2004@gmail.com
  reminder-duration-fallback: PT1M
  user-service:
    url: http://localhost:8082

flowable:
  database-schema-update: true
  async-executor-activate: true
  idm:
    enabled: false
  process-definition-location-prefix: classpath*:/processes/
  process-definition-location-suffixes:
    - '**.bpmn'
    - '**.bpmn20.xml'
  admin:
    app:
      server-config:
        name: leave-service
        description: Leave Management Service
        server-address: http://localhost
        port: 8083
        context-root: /
        rest-root: api
  task:
    app:
      server-config:
        name: leave-service
        description: Leave Management Service
        server-address: http://localhost
        port: 8083
        context-root: /
        rest-root: api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
